import {
  Table, TableContainer, Tbody, Td, Th, Thead, Tr
} from '@chakra-ui/react';
import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import prisma from '../../src/libs/prisma';
const PortfoliosTable = (props: any) => {
  return <TableContainer>
    <Table variant='simple'>
      <Thead>
        <Tr>
          <Th>Titre</Th>
          <Th>Description</Th>
          <Th>Nombre de transaction</Th>

        </Tr>
      </Thead>
      <Tbody>
        {props.portfolios.map((portfolio: any) => {
          return <Tr key={portfolio.id}>
            <Td>{portfolio.title}</Td>
            <Td>{portfolio.description}</Td>
            <Td>{portfolio.transactions.length}</Td>
          </Tr>
        })}
      </Tbody>
    </Table>
  </TableContainer>
}

const Home: NextPage = ({ portfolios }: any) => {


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PortfoliosTable portfolios={portfolios}></PortfoliosTable>

    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const portfolios = await prisma.portfolio.findMany({
    include: {
      transactions: {
        select: { id: true },
      },
    },
  });
  return { props: { portfolios } };
}

export default Home;
