import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import axios from 'axios';
import { fetcherUsingAxios } from '../src/libs/utils';
import {
  Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
} from '@chakra-ui/react'
import { useEffect } from 'react';
import { useCoinsMarkets } from '../src/hooks/apiHooks';
import { ECurrency, ICoin } from '../src/types/apiTypes';
import ColorNumber from '../src/components/ColorNumber/ColorNumber';
import Navbar from '../src/components/Navbar/Navbar';
const TableTop20Coins = () => {

  const { coins, isLoading, isError } = useCoinsMarkets(ECurrency.USD);
  return <TableContainer>
    <Table variant='simple'>
      <Thead>
        <Tr>
          <Th>icone</Th>
          <Th>id</Th>
          <Th>symbole</Th>
          <Th>nom</Th>
          <Th>% en 24h</Th>
          <Th>% en 7j</Th>
          <Th>% en 30j</Th>
          <Th>% en 1 an</Th>
          <Th>prix</Th>
        </Tr>
      </Thead>
      <Tbody>
        {coins && coins.map((coin: ICoin, key: string) => <Tr key={key}>
          <Td><img src={coin.image} height="40px" width="40px"></img></Td>
          <Td>{coin.id}</Td>
          <Td>{coin.symbol}</Td>
          <Td>{coin.name}</Td>
          <Td><ColorNumber number={coin.price_change_percentage_24h.toFixed(4)}></ColorNumber> %</Td>
          <Td><ColorNumber number={coin.price_change_percentage_7d_in_currency.toFixed(4)}></ColorNumber> %</Td>
          <Td><ColorNumber number={coin.price_change_percentage_30d_in_currency?.toFixed(4)}></ColorNumber> %</Td>
          <Td><ColorNumber number={coin.price_change_percentage_1y_in_currency?.toFixed(4)}></ColorNumber> %</Td>
          <Td>{coin.current_price} $</Td>
        </Tr>)}
      </Tbody>
    </Table>
  </TableContainer>
}
const Home: NextPage = () => {


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TableTop20Coins></TableTop20Coins>

    </div>
  )
}

export default Home
